#######  
### => Generated by mindmatters_story_writer
#######

require File.dirname(__FILE__) + "/helper"


steps_for(:admin_invites_company) do
  
  Given "a company exists" do
    @company = create_company
  end
  
  Given "the user is logged in" do
    login
  end
  
  Given "the user is a admin" do
    @user.has_role 'admin'
  end
  
  Given "the user is on companies overview" do
    get '/companies'
  end
  
  When "he clicks onto the invite company link" do
    post "companies/#{@company.id}/invite"
  end
  
  Then "the response should be redirect" do
    response.should be_redirect
  end
  
  Then "the email is sent" do
    UserMailer.should_receive(:deliver_company_invitation).with(@company)
  end
  
  Then "the flag invited_at is set to the current date" do
    @company.reload
    @company.invited_at.should_not be_nil
  end
  
  Then "the flash should be set" do
    flash[:notice].should_not be_blank
  end
  
end

with_steps_for(:admin_invites_company) do
  run_local_story "admin_story", :type => RailsStory
end
